bassem_first_homepage:
    path:     /
    defaults: { _controller: BassemFirstBundle:Default:index }

bassem_premierpage:
    path:     /premier/{nom}
    defaults: { _controller: BassemFirstBundle:Default:premier }